apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  APP_ENV: UFJPRA==
  APP_HOST: ""
  APP_PORT: NTAwMA==
  JWT_SECRET: SyVsdmltUV5vPEFfeTZI
  DB_NAME: ZGIwMQ==
  DB_HOST: bG9jYWxob3N0
  DB_PORT: NTQzMg==
  DB_USER: cG9zdGdyZXM=
  DB_PASS: NiU+ZnZ6Z0YmWV9aUV1VYw==
  RD_HOST: cmVkaXMtc2VydmljZQ==
  RD_PORT: NjM3OQ==
  RD_PASS: VTM2RjVNak5paWtLZlp1cg==
  RD_DATA: MA==
