FROM golang:1.21-alpine as builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o server

#Second build stage
FROM alpine:3.18

WORKDIR /app

COPY --from=builder /app/server /app/server

EXPOSE 5000

CMD ["./server"]